Scripts rewritten

diff --git a/bin/cn-date-to-slot b/bin/cn-date-to-slot
--- a/bin/cn-date-to-slot
+++ b/bin/cn-date-to-slot
@@ -10,35 +10,56 @@ set -o pipefail
 slot0sec=1591566291 # Slot 0 seconds since 1970-01-01 00:00:00 UTC
 
 function usage() {
-  echo "Display Cardano slot corresponding to date" 2>&1
-  echo "Usage: $(basename $0) 'YYYY-MM-DD HH:MM:SS.nnn UTC'" 2>&1
-  echo "Current timezone is assumed if not supplied" 2>&1
-  echo 2>&1
-  echo "Eg: $(basename $0) '2020-07-29 21:44:51 UTC'" 2>&1
-  echo 2>&1
+  cat << END_OF_USAGE >&2
+Usage: $(basename $0) 'YYYY-MM-DD HH:MM:SS.nnn'"
+Display Cardano slot corresponding to date
+
+    -h, --help        display this help and exit
+
+Examples:
+  $(basename $0) '2020-07-29 21:44:51 UTC'"
+  $(basename $0) '2020-07-29 21:44:51.123456789'"
+When no timezone, local timezone assumed.
+
+END_OF_USAGE
+}
+
+function err_exit() {
+  printf '%s\n' "$1" >&2
+  exit "${2:-1}"
 }
 
 function dateToSlot() {
   local datetime decimal unixtime formatStr
   datetime="${1}"
   if [[ ! "${datetime}" =~ ^[-0-9]+\ [:0-9]+(\.[0-9]+)?( [A-Z]+)?$ ]]; then
-    printf '%s\n' 'Date malformed'
-    return 1
+    return 1 # malformed date
   fi
-  if [[ -n "${BASH_REMATCH[1]:-}" ]]; then
-    decimal="${BASH_REMATCH[1]#.}"
+  if [[ -n "${BASH_REMATCH[1]:-}" ]]; then # is there fractional seconds
+    decimal="${BASH_REMATCH[1]#.}" # how many digits in fractional seconds
     formatStr="+%s.%${#decimal}N"
   else
     formatStr='+%s'
   fi
-  unixtime="$( date -d "${datetime}" "${formatStr}" )" # Error date malformed
+  unixtime="$( date -d "${datetime}" "${formatStr}" )" # Error if date malformed
   printf '%s\n' "$( echo "${unixtime} - ${slot0sec}" | bc )"
   return 0
 }
 
-# Should be valid date command line argument remaining
-if [[ $# = 1 ]]; then
-  dateToSlot "${1}" && exit 0
+# Process optional command line arguments
+while [[ $# -gt 0 && "${1:0:1}" = '-' ]]; do
+  opt="${1}"
+  shift
+  case "${opt}" in
+    '-h' | '--help' ) usage; exit 0;;
+    * ) printf '%s\n' "Invalid option: '${opt}'" >&2; err_exit "Try '$(basename $0) --help' for more information";;
+  esac
+done
+
+# Should be only valid date command line argument remaining
+if [[ $# != 1 ]]; then
+  err_exit "Try '$(basename $0) --help' for more information"
 fi
-usage
-exit 1
+
+dateToSlot "$1" || err_exit "Date malformed"
+
diff --git a/bin/cn-leaderlog b/bin/cn-leaderlog
--- a/bin/cn-leaderlog
+++ b/bin/cn-leaderlog
@@ -1,44 +1,71 @@
 #!/bin/bash
-# Author: terminada.io 20220704, updated 20221203
+# Author: terminada.io 20220704, updated 20240331
 set -o errexit
 set -o pipefail
 set -o nounset
 
-# CARDANO_NODE_SOCKET_PATH='/run/cardano/mainnet-node.socket' cardano-cli query leadership-schedule --mainnet --genesis /etc/cardano/mainnet-shelley-genesis.json --stake-pool-id "blahblahblah" --vrf-signing-key-file /etc/cardano/private/vrf.skey --current
+# CARDANO_NODE_SOCKET_PATH='/run/cardano/mainnet/node.socket' cardano-cli query leadership-schedule --mainnet --genesis /etc/cardano/mainnet/shelley-genesis.json --stake-pool-id "blahblahblah" --vrf-signing-key-file /etc/cardano/private/vrf.skey --current
 
 CONFIG_DIR='/etc/cardano' #FIXME
 CONFIG_NET='mainnet' #FIXME mainnet|preprod|preview
-export CARDANO_NODE_SOCKET_PATH="/run/cardano/${CONFIG_NET}-node.socket" #FIXME
+export CARDANO_NODE_SOCKET_PATH="/run/cardano/${CONFIG_NET}/node.socket" #FIXME
 pool_vrf_skey="${CONFIG_DIR}/private/vrf.skey" #FIXME
-shelley_genesis="${CONFIG_DIR}/${CONFIG_NET}-shelley-genesis.json"
+shelley_genesis="${CONFIG_DIR}/${CONFIG_NET}/shelley-genesis.json"
 nwmagic="$(jq -r '.networkMagic' "${shelley_genesis}")"
-config="${CONFIG_DIR}/my-cardano-node-config.json" #FIXME
-
-# Check poolId defined in config
-[[ -f "$config" ]] || { echo "Config: $config doesn't exist."; exit 1; }
-pool_id="$(jq -r '.poolId' "$config" 2>/dev/null)"
-if [[ -z "${pool_id:-}" || "$pool_id" == 'null' ]]; then
-  echo "Config: $config must contain poolId"
-  exit 1
-fi
+pool_id_file="${CONFIG_DIR}/${CONFIG_NET}/pool-id" #FIXME
 
 function usage() {
-  echo "Usage: $(basename $0) current | next" 2>&1
-  echo 'Generates leaderlog for current or next epoch'
-  echo
+  cat << END_OF_USAGE >&2
+Usage: $(basename $0) current | next
+Generates leaderlog for current or next epoch
+
+    -h, --help        display this help and exit
+
+END_OF_USAGE
 }
 
-optstring=":h"
-while getopts ${optstring} arg; do
-  case ${arg} in
-    h) usage; exit 0;;
-    ?) echo "Invalid options: -${OPTARG}."; echo; usage; exit 1;;
+function err_exit() {
+  printf '%s\n' "$1" >&2
+  exit "${2:-1}"
+}
+
+function file_key_value() {
+  local f k v
+  f="$1"
+  k="$2"
+  if [[ -z "${f:-}" || -z "${k:-}" || ! -f "${f}" ]]; then
+    return 1
+  fi
+  while read -r line; do
+    v="$(printf '%s\n' "${line}" | sed -nr "s/^\s*${k}\s*=\s*["\""']?([^[:space:]"\""']+)["\""']?\s*(#.*)?$/\1/p")"
+    if [ -n "${v:-}" ]; then
+      break
+    fi
+  done <<< "$(grep -Ev '^\s*#|^\s*$' "${f}")" # Skip comment and blank lines
+  if [ -z "${v:-}" ]; then
+    return 1
+  fi
+  printf '%s\n' "${v}"
+  return 0
+}
+
+# Process optional command line arguments
+while [[ $# -gt 0 && "${1:0:1}" = '-' ]]; do
+  opt="${1}"
+  shift
+  case "${opt}" in
+    '-h' | '--help' ) usage; exit 0;;
+    * ) printf '%s\n' "Invalid option: '${opt}'" >&2; err_exit "Try '$(basename $0) --help' for more information";;
   esac
 done
 
-if [[ $(( $# - $OPTIND )) -ne 0 ]]; then usage; exit 1; fi
-epoch=${@:$OPTIND:1}
-if ! [[ "$epoch" =~ ^(current|next)$ ]]; then usage; exit 1; fi
+# Should be only current | next command line argument remaining
+if [[ $# != 1 || ! "${1}" =~ ^(current|next)$ ]]; then
+  err_exit "Try '$(basename $0) --help' for more information"
+fi
+epoch="$1"
+
+pool_id="$(file_key_value "${pool_id_file}" 'POOL_ID')" || err_exit "${pool_id_file} must contain POOL_ID=VALUE"
 
 epoch_nr="$(cardano-cli query tip --testnet-magic "${nwmagic}" | jq '.epoch')"
 if [[ "$epoch" == 'next' ]]; then (( epoch_nr++ )); fi
@@ -59,4 +86,3 @@ done < <(nice -n 15 cardano-cli query leadership-schedule --testnet-magic "${nwm
 printf -- '--------------------------------------\n'
 printf 'Total: %d assigned slots.\n' "$count"
 
-exit 0
diff --git a/bin/cn-monitor-block-delay b/bin/cn-monitor-block-delay
--- a/bin/cn-monitor-block-delay
+++ b/bin/cn-monitor-block-delay
@@ -1,61 +1,69 @@
 #!/bin/bash
-# Author: terminada.io 20211031 updated 20221203
+# Author: terminada.io 20211031 updated 20240331
 set -o nounset
 set -o errexit
 set -o pipefail
 
 CONFIG_DIR='/etc/cardano' #FIXME
 CONFIG_NET='mainnet' #FIXME mainnet|preprod|preview
-export CARDANO_NODE_SOCKET_PATH="/run/cardano/${CONFIG_NET}-node.socket"
-# If sending to pooltool config must contain {poolId:, pooltoolApiKey:}
-config="${CONFIG_DIR}/my-cardano-node-config.json" #FIXME {poolId:, pooltoolApiKey:}
+export CARDANO_NODE_SOCKET_PATH="/run/cardano/${CONFIG_NET}/node.socket"
+# If sending to pooltool then must set POOL_ID and POOLTOOL_API_KEY
+pool_id_file="${CONFIG_DIR}/${CONFIG_NET}/pool-id" #FIXME
+pooltool_api_key_file="${CONFIG_DIR}/${CONFIG_NET}/pooltool-api-key" #FIXME
+node_id_file="${CONFIG_DIR}/${CONFIG_NET}/node-id" #FIXME
 
 # https://forum.cardano.org/t/and-so-it-begins-reflections-on-this-first-shelley-epoch/37544
 # Shelley first slot: "2020-07-29 21:44:51 UTC", epoch 208, slot 4492800
-# echo $(date -d"2020-07-29 21:44:51 UTC" "+%s") - 4492800 | bc # == 1591566291
+# printf '%s\n' "$(date -d"2020-07-29 21:44:51 UTC" "+%s") - 4492800" | bc # == 1591566291
 slot0sec=1591566291 # Slot 0 seconds since 1970-01-01 00:00:00 UTC
 
 function usage() {
-  echo "Usage: $(basename $0) [-s]" 2>&1
-  echo 'Log cardano-node block delay'
-  echo '  -s     Send information to pooltool.io'
-  echo
+  cat << END_OF_USAGE >&2
+Usage: $(basename $0) [-s | --send]
+Follow system journal and print delay ms as each block added to tip
+
+    -s, --send        send information to pooltool.io
+    -h, --help        display this help and exit
+
+END_OF_USAGE
 }
 
-optstring=':s'
-while getopts ${optstring} arg; do
-  case ${arg} in
-    s) optsend='true';;
-    h) usage && exit 0;;
-    ?) echo "Invalid options: -${OPTARG}."; echo; usage && exit 1;;
-  esac
-done
+function err_exit() {
+  printf '%s\n' "$1" >&2
+  exit "${2:-1}"
+}
 
-# If sending to pooltool, set variables required
-if [[ "${optsend:-}" == "true" ]]; then
-  if [[ -f "$config" ]]; then
-    pool_id="$(jq -r '.poolId' "$config" 2>/dev/null)"
-    api_key="$(jq -r '.pooltoolApiKey' "$config" 2>/dev/null)"
-    node_id="$(jq -r '.nodeId' "$config" 2>/dev/null)"
+function file_key_value() {
+  local f k v
+  f="$1"
+  k="$2"
+  if [[ -z "${f:-}" || -z "${k:-}" || ! -f "${f}" ]]; then
+    return 1
   fi
-  if [[ -z "${pool_id:-}" || "$pool_id" == 'null' || -z "${api_key:-}" || "$api_key" == 'null' ]]; then
-    echo "Config: $config must contain poolId and pooltoolApiKey"
-    exit 1
+  while read -r line; do
+    v="$(printf '%s\n' "${line}" | sed -nr "s/^\s*${k}\s*=\s*["\""']?([^[:space:]"\""']+)["\""']?\s*(#.*)?$/\1/p")"
+    if [ -n "${v:-}" ]; then
+      break
+    fi
+  done <<< "$(grep -Ev '^\s*#|^\s*$' "${f}")" # Skip comment and blank lines
+  if [ -z "${v:-}" ]; then
+    return 1
   fi
-  platform="monitor-block-delay"
-  [[ "$(cardano-cli version)" =~ cardano-cli\ ([\.0-9]+)\ .*rev\ ([a-f0-9]+)$ ]]
-  version="${BASH_REMATCH[1]}:${BASH_REMATCH[2]:0:5}"
-fi
+  printf '%s\n' "${v}"
+  return 0
+}
 
 function write_log() {
-  local hash=$1; local slot=$2; local block=$3; local delay=$4
+  local hash slot block delay
+  hash=$1; slot=$2; block=$3; delay=$4
   printf 'Hash=%s,Slot=%d,Block=%d,Delayed=%0.3f\n' "$hash" "$slot" "$block" "$delay"
 }
 
 function send_pooltool() {
-  local hash=$1; local slot=$2; local block=$3; local delay=$4
+  local hash slot block delay
+  hash="$1"; slot="$2"; block="$3"; delay="$4"
   # Calculate time from slot + delay and round to 3 decimal places
-  timestamp="$(printf '%.3f' $(echo "$slot0sec + $slot + $delay" | bc))"
+  timestamp="$(printf '%.3f' $(printf '%s\n' "$slot0sec + $slot + $delay" | bc))"
   datetime="$(date --utc --date=@${timestamp} +"%FT%T.%3NZ")"
   json="$(jq -cn --arg apiKey "$api_key" --arg poolId "$pool_id" \
     --arg nodeId "$node_id" --arg version "$version" --arg at "$datetime" \
@@ -63,12 +71,33 @@ function send_pooltool() {
     --arg blockHash "$hash" --arg platform "$platform" \
     '{apiKey: $apiKey, poolId: $poolId, data: {nodeId: $nodeId, version: $version, at: $at, blockNo: $blockNo | tonumber, slotNo: $slotNo | tonumber, blockHash: $blockHash, platform: $platform}}')"
   response="$(curl -s -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "$json" 'https://api.pooltool.io/v0/sendstats' || true)" # '' if curl fails
-  success="$(echo "${response:-}" | jq -r '.success')"
-  if [[ "$success" == 'true' ]]; then result=success; else result=failure; fi;
+  success="$(printf '%s\n' "${response:-}" | jq -r '.success')"
+  if [[ "$success" == 'true' ]]; then result='success'; else result='failure'; fi;
   printf 'Sent pooltool: %s Response: %s\n' "hash=${hash},slot=${slot},block=${block},datetime=${datetime}" "$result"
 }
 
-echo "$(basename $0) started:"
+# Process optional command line arguments
+while [[ $# -gt 0 && "${1:0:1}" = '-' ]]; do
+  opt="${1}"
+  shift
+  case "${opt}" in
+    '-s' | '--send' ) optsend='true';;
+    '-h' | '--help' ) usage; exit 0;;
+    * ) printf '%s\n' "Invalid option: '${opt}'" >&2; err_exit "Try '$(basename $0) --help' for more information";;
+  esac
+done
+
+# If sending to pooltool, set variables required
+if [[ "${optsend:-}" == "true" ]]; then
+  pool_id="$(file_key_value "${pool_id_file}" 'POOL_ID')" || err_exit "${pool_id_file} must contain POOL_ID=VALUE"
+  api_key="$(file_key_value "${pooltool_api_key_file}" 'POOLTOOL_API_KEY')" || err_exit "${pooltool_api_key_file} must contain POOLTOOL_API_KEY=VALUE"
+  node_id="$(file_key_value "${node_id_file}" 'NODE_ID')" || node_id='' # default
+  platform="$(basename $0)"
+  [[ "$(cardano-cli --version)" =~ cardano-cli\ ([\.0-9]+)\ .*rev\ ([a-f0-9]+)$ ]] || err_exit 'cardano-cli --version error'
+  version="${BASH_REMATCH[1]}:${BASH_REMATCH[2]:0:5}"
+fi
+
+printf '%s\n' "$(basename $0) following journal:"
 
 # regex for log when new block received "Chain extended, new tip:"
 regex='\[([-0-9]+)\ ([\.:0-9]+)\ UTC\]\ Chain\ extended,\ new\ tip:\ ([a-f0-9]+)\ at\ slot\ ([0-9]+)$'
@@ -81,12 +110,11 @@ while IFS= read -r line; do
   logslot="${BASH_REMATCH[4]}"
   [[ "${loghash}" != "${lasthash}" ]] || continue # skip log if same block
   lasthash="$loghash"
-  # Get delay and other data from cardano-node EKGView
-  read block ekgslot delay < <(echo $(curl -s -H 'Accept: application/json' http:/localhost:12788 | jq -r '.cardano.node.metrics | .blockNum.int.val, .slotNum.int.val, .blockfetchclient.blockdelay.s.val'))
+  # Get data from EKGView. \(.val) syntax for jq string interpolation
+  read -r block ekgslot delay < <(curl -s -H 'Accept: application/json' http:/localhost:12788 | jq -r '.cardano.node.metrics | "\(.blockNum.int.val) \(.slotNum.int.val) \(.blockfetchclient.blockdelay.s.val)"')
   [[ "${ekgslot:-}" == "${logslot:-}" ]] || continue # skip if slots differ
-  [[ -z "${delay:-}" || "$delay" == 'null' || -z "${block:-}" || "$block" == 'null' ]] && continue # skip if empty or null
+  [[ -z "${delay:-}" || "$delay" == 'null' || -z "${block:-}" || "$block" == 'null' ]] && continue # skip empty or null
   write_log "$loghash" "$ekgslot" "$block" "$delay"
-  if [[ "${optsend:-}" == 'true' ]]; then
-    send_pooltool "$loghash" "$ekgslot" "$block" "$delay"
-  fi
+  [[ "${optsend:-}" == 'true' ]] && send_pooltool "$loghash" "$ekgslot" "$block" "$delay"
 done < <(journalctl -fn0 -u cardano-node)
+
diff --git a/bin/cn-slot-to-date b/bin/cn-slot-to-date
--- a/bin/cn-slot-to-date
+++ b/bin/cn-slot-to-date
@@ -10,12 +10,24 @@ set -o pipefail
 slot0sec=1591566291 # Slot 0 seconds since 1970-01-01 00:00:00 UTC
 
 function usage() {
-  echo "Display date corresponding to Cardano slot" 2>&1
-  echo "Usage: $(basename $0) [-u|--utc] 'slot'" 2>&1
-  echo "           -u,--utc   For timezone UTC" 2>&1
-  echo 2>&1
-  echo "Eg: $(basename $0) -u '4492800'" 2>&1
-  echo 2>&1
+  cat << END_OF_USAGE >&2
+Usage: $(basename $0) [-u|--utc] slotnumber"
+Display date corresponding to Cardano slot number
+
+    -u, --utc         For timezone UTC
+    -h, --help        display this help and exit
+
+Examples:
+  $(basename $0) 4492800
+  $(basename $0) --utc 4492800.123456789
+If no -u,--utc switch, local timezone assumed.
+
+END_OF_USAGE
+}
+
+function err_exit() {
+  printf '%s\n' "$1" >&2
+  exit "${2:-1}"
 }
 
 UTC=''
@@ -23,15 +35,10 @@ UTC=''
 while [[ $# -gt 0 && "${1:0:1}" = '-' ]]; do
   opt="${1}"
   shift
- case "${opt}" in
-     '-u' | '--utc' )
-      UTC='--utc'
-      ;;
-    * )
-      printf '%s\n\n' "Invalid option: ${opt}" >&2
-      usage
-      exit 1
-      ;;
+  case "${opt}" in
+    '-u' | '--utc' ) UTC='--utc';;
+    '-h' | '--help' ) usage; exit 0;;
+    * ) printf '%s\n' "Invalid option: '${opt}'" >&2; err_exit "Try '$(basename $0) --help' for more information";;
   esac
 done
 
@@ -39,8 +46,7 @@ function slotToDate() {
   local slot decimal formatStr
   slot="${1}" # might contain decimal
   if [[ ! "${slot}" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
-    printf '%s\n' "slot number malformed"
-    return 1
+    return 1 # malformed slot number
   fi
   slot="$( echo "${slot0sec} + ${slot}" | bc )"
   decimal="${slot#*.}"
@@ -53,9 +59,20 @@ function slotToDate() {
   return 0
 }
 
-# Should be single slot number command line argument remaining
-if [[ $# = 1 ]]; then
-  slotToDate "${1}" && exit 0
+# Process optional command line arguments
+while [[ $# -gt 0 && "${1:0:1}" = '-' ]]; do
+  opt="${1}"
+  shift
+  case "${opt}" in
+    '-h' | '--help' ) usage; exit 0;;
+    * ) printf '%s\n' "Invalid option: '${opt}'" >&2; err_exit "Try '$(basename $0) --help' for more information";;
+  esac
+done
+
+# Should be only valid slot number command line argument remaining
+if [[ $# != 1 ]]; then
+  err_exit "Try '$(basename $0) --help' for more information"
 fi
-usage
-exit 1
+
+slotToDate "$1" || err_exit "Slot number malformed"
+
